In [1]:
import numpy as np
import tensorflow as tf

In [2]:
a = np.arange(20).reshape(5, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [4]:
tensor_a = tf.Variable(a)
embedded_tensor = tf.nn.embedding_lookup(params=tensor_a, ids=[0,3,2,1])
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    embedded_tensor = sess.run(embedded_tensor)
    print(embedded_tensor)

[[ 0  1  2  3]
 [12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]]
