In [1]:
import numpy as np

In [2]:
from common.functions import softmax, cross_entropy_error
from common.functions import numerical_gradient

神经网络的梯度：<p/>
权重矩阵W：<p/>
$ 
\begin{split}
W = \begin{pmatrix} 
w_{11} & w_{12} & w_{13} \\ 
w_{21} & w_{22} & w_{23} \\ 
\end{pmatrix} 
\end{split}
$ <p/>
损失函数L关于权重参数的梯度：<p/>
$
\begin{split}
\dfrac{\delta L}{\delta W} = \begin{pmatrix}
\dfrac{\delta L}{\delta w_{11}} & \dfrac{\delta L}{\delta w_{12}} & \dfrac{\delta L}{\delta w_{13}} \\
\dfrac{\delta L}{\delta w_{21}} & \dfrac{\delta L}{\delta w_{22}} & \dfrac{\delta L}{\delta w_{23}} \\
\end{pmatrix}
\end{split}
$

In [12]:
class SimpleNet:
    
    def __init__(self):
        # 符合正太分布的随机数矩阵
        self.W = np.random.randn(2, 3)
        self.W = self.init_weight()
        
    def init_weight(self):
        return np.array([[0.47355232,0.9977393,0.84668094],
                         [0.85557411,0.03563661,0.69422093]])
    
    def predict(self, x):
        # 输入与权重矩阵的点积运算
        y = np.dot(x, self.W)
        return y
    
    def loss(self, x, t):
#         print('enter - loss, x =', x, 't =', t)
#         print('enter - loss, W =', self.W)
        # 求预测值
        z = self.predict(x)
        print('enter - loss, predict =', z)
        # 多分类
        y = softmax(z)
        print('enter - loss, softmax =', y)
        # 交叉熵误差
        l = cross_entropy_error(y, t)
        print('enter - loss, cross_entropy_error =', l)
        return l

In [13]:
net = SimpleNet()
print(net.W)
# print(net.W.size)

[[0.47355232 0.9977393  0.84668094]
 [0.85557411 0.03563661 0.69422093]]


In [14]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[1.05414809 0.63071653 1.1328074 ]


In [15]:
y = np.argmax(p)
print(y)

2


In [16]:
t = np.zeros_like(p)
t[y] = 1
print(t)
# print(net.loss(x, t))
# print(x.size)
# print(t.size)

[0. 0. 1.]


In [18]:
# 损失函数
def loss_fucntion(W):
    print('lost_function -->')
    # SimpleNet.loss
    l = net.loss(x, t)
    print('lost_function -->', l, '\n')
    return l

# 求损失函数的梯度
dW = numerical_gradient(loss_fucntion, net.W)
print('dW=', dW)


lost_function -->
enter - loss, predict = [1.05405809 0.63056653 1.1326574 ]
enter - loss, softmax = [0.36542662 0.23926553 0.39530784]
enter - loss, cross_entropy_error = 0.928090210960927
lost_function --> 0.928090210960927 

lost_function -->
enter - loss, predict = [1.05393809 0.63056653 1.1326574 ]
enter - loss, softmax = [0.3653988  0.23927602 0.39532518]
enter - loss, cross_entropy_error = 0.9280463614466788
lost_function --> 0.9280463614466788 

lost_function -->
enter - loss, predict = [1.05393809 0.63062653 1.1326574 ]
enter - loss, softmax = [0.36539355 0.23928694 0.3953195 ]
enter - loss, cross_entropy_error = 0.9280607183320589
lost_function --> 0.9280607183320589 

lost_function -->
enter - loss, predict = [1.05393809 0.63050653 1.1326574 ]
enter - loss, softmax = [0.36540404 0.2392651  0.39533085]
enter - loss, cross_entropy_error = 0.9280320052165812
lost_function --> 0.9280320052165812 

lost_function -->
enter - loss, predict = [1.05393809 0.63050653 1.1327174 ]
enter

In [19]:
a = np.array([[1,2],[3,4]])
print(np.sum(a**2))
print(np.sum(a**2, axis=1))
print(np.sum(a**2, axis=0))

30
[ 5 25]
[10 20]


In [20]:
for i, x in enumerate(a):
    print('i=', i, 'x=', x)

i= 0 x= [1 2]
i= 1 x= [3 4]


In [21]:
for i in range(a.shape[0]):
    print(a[i])

[1 2]
[3 4]
