In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
sess = tf.Session()

In [7]:
x_vals = np.array([1., 3., 5., 7., 9.])
x_data = tf.placeholder(tf.float32)
m_const = tf.constant(3.)
my_product = x_data * m_const # tf.mul 函数已经没有了
for x_val in x_vals:
    print(sess.run(my_product, feed_dict={x_data: x_val}))

3.0
9.0
15.0
21.0
27.0


In [8]:
my_array = np.array([[1., 3., 5., 7., 9.],
                    [-2., 0., 2., 4., 6.],
                    [-6., -3., 0., 3., 6]])
x_vals = np.array([my_array, my_array + 1])
x_data = tf.placeholder(tf.float32, shape=(3, 5))

In [9]:
m1 = tf.constant([[1.], [0.], [-1.], [2.], [4.]])
m2 = tf.constant([[2.]])
a1 = tf.constant([[10.]])

In [10]:
prod1 = tf.matmul(x_data, m1)
prod2 = tf.matmul(prod1, m2)
add1 = tf.add(prod2, a1)

In [11]:
for x_val in x_vals:
    print(sess.run(add1, feed_dict={x_data: x_val}))

[[102.]
 [ 66.]
 [ 58.]]
[[114.]
 [ 78.]
 [ 70.]]


In [12]:
# Working with Multiple Layers
x_shape = [1, 4, 4, 1]
x_val = np.random.uniform(size=x_shape)

In [13]:
x_val

array([[[[0.19239633],
         [0.69248434],
         [0.52245793],
         [0.23869087]],

        [[0.21772611],
         [0.31477096],
         [0.07113111],
         [0.358983  ]],

        [[0.20903022],
         [0.75166904],
         [0.31383752],
         [0.49622061]],

        [[0.51015665],
         [0.97378378],
         [0.56335926],
         [0.74220931]]]])

In [14]:
x_data = tf.placeholder(tf.float32, shape=x_shape)

In [15]:
x_data

<tf.Tensor 'Placeholder_4:0' shape=(1, 4, 4, 1) dtype=float32>

In [16]:
my_filter = tf.constant(0.25, shape=[2,2,1,1])
my_strides = [1, 2, 2, 1]
mov_avg_layer = tf.nn.conv2d(x_data, my_filter, my_strides,
                            padding='SAME''', name='Moving_Avg_Window')

In [17]:
# define a custom layer
def custom_layer(input_matrix):
    input_matrix_sqeezed = tf.squeeze(input_matrix)
    A = tf.constant([[1., 2.], [-1., 3.]])
    b = tf.constant(1., shape=[2,2])
    temp1 = tf.matmul(A, input_matrix_sqeezed)
    temp = tf.add(temp1, b) # Ax + b
    return(tf.sigmoid(temp))

In [18]:
with tf.name_scope('Custom_Layer') as scope:
    custom_layer1 = custom_layer(mov_avg_layer)

In [19]:
sess.run(custom_layer1, feed_dict={x_data: x_val})

array([[0.9293446, 0.9133806],
       [0.9226661, 0.9079539]], dtype=float32)

In [20]:
# implementing Loss Functions
import matplotlib.pyplot as plt

In [21]:
x_vals = tf.linspace(-1., 1., 500)
target = tf.constant(0.)

In [22]:
# L2 norm loss
l2_y_vals = tf.square(target - x_vals)
l2_y_out = sess.run(l2_y_vals)

In [23]:
# L1 norm loss
l1_y_vals = tf.abs(target - x_vals)
l1_y_out = sess.run(l1_y_vals)

In [24]:
# Pseudo-Huber loss
# delta1
delta1 = tf.constant(0.25)
phuber1_y_vals = tf.multiply(tf.square(delta1), 
                             tf.sqrt(1. + tf.square((target - x_vals) / delta1)) - 1.)
phuber1_y_out = sess.run(phuber1_y_vals)

# delta2
delta2 = tf.constant(5.)
phuber2_y_vals = tf.multiply(tf.square(delta2), 
                             tf.sqrt(1. + tf.square((target - x_vals) / delta2)) - 1.)
phuber2_y_out = sess.run(phuber2_y_vals)


In [26]:
# Hinge loss
x_vals = tf.linspace(-3., 5., 500)
target = tf.constant(1.)
targets = tf.fill([500,], 1.)

In [27]:
hinge_y_vals = tf.maximum(0., 1. - tf.multiply(target, x_vals))
hinge_y_out = sess.run(hinge_y_vals)

In [29]:
# Cross-entropy loss
xentroy_y_vals = - tf.multiply(target, tf.log(x_vals)) - tf.multiply((1. - target), tf.log(1. - x_vals))
xentroy_y_out = sess.run(xentroy_y_vals)

In [35]:
# Sigmoid cross entropy loss
xentropy_sigmoid_y_vals = tf.nn.sigmoid_cross_entropy_with_logits(
    logits=x_vals, labels=targets)
xentropy_sigmoud_y_out = sess.run(xentropy_sigmoid_y_vals)
# xentropy_sigmoud_y_out