In [2]:
import tensorflow as tf
import numpy as np

In [3]:
zero_tsr = tf.zeros([3,2])

In [4]:
zero_tsr

<tf.Tensor 'zeros:0' shape=(3, 2) dtype=float32>

In [5]:
ones_tsr = tf.ones([2,4])

In [6]:
ones_tsr.shape

TensorShape([Dimension(2), Dimension(4)])

In [7]:
constant_tsr = tf.constant([1,23])

In [8]:
constant_tsr

<tf.Tensor 'Const:0' shape=(2,) dtype=int32>

In [11]:
linear_tsr = tf.linspace(0., 10., num=5)

In [12]:
my_var = tf.Variable(tf.zeros([2,3]))
sess = tf.Session()
initialize_op = tf.global_variables_initializer()
sess.run(initialize_op)

In [13]:
my_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32_ref>

In [14]:
sess = tf.Session()
x = tf.placeholder(tf.float32, shape=[2,3])
y = tf.identity(x)
x_vals = np.random.rand(2,3)
sess.run(y, feed_dict={x: x_vals})

array([[0.53882915, 0.2508245 , 0.29023498],
       [0.74255884, 0.15669236, 0.48261687]], dtype=float32)

In [15]:
sess = tf.Session()
first_var = tf.Variable(tf.zeros([2,3]))
sess.run(first_var.initializer)

In [16]:
second_var = tf.Variable(tf.zeros_like(first_var))
sess.run(second_var.initializer)

In [17]:
identity_matrix = tf.diag([1.0, 2.0, 1.0])
A = tf.truncated_normal([2, 3])
B = tf.fill([2, 3], 5.0)
C = tf.random_uniform([3, 2])
D = tf.convert_to_tensor(np.array([[1., 2., 3.],
                                  [-3., -7., -1.],
                                  [0., 5., -2.]]))


In [18]:
sess.run(identity_matrix)

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 1.]], dtype=float32)

In [19]:
sess.run(A)

array([[ 0.2718225 , -0.82903105, -0.7835672 ],
       [ 0.5782463 ,  1.1890864 ,  1.2035238 ]], dtype=float32)

In [20]:
sess.run(B)

array([[5., 5., 5.],
       [5., 5., 5.]], dtype=float32)

In [21]:
sess.run(C)

array([[0.9273015 , 0.5398363 ],
       [0.41530454, 0.22284198],
       [0.86614907, 0.97786725]], dtype=float32)

In [22]:
sess.run(D)

array([[ 1.,  2.,  3.],
       [-3., -7., -1.],
       [ 0.,  5., -2.]])

In [23]:
sess.run(tf.matrix_determinant(D))

-37.99999999999999

In [24]:
sess.run(A+B)

array([[5.1821957, 5.286034 , 5.5263896],
       [5.940963 , 5.272182 , 6.3380127]], dtype=float32)

In [25]:
sess.run(A*B)

array([[ 0.39351103, -4.0889306 , -0.499304  ],
       [ 1.5447917 , -1.7308484 ,  5.8496456 ]], dtype=float32)

In [26]:
sess.run(tf.matmul(A, identity_matrix))

array([[ 0.22405478, -1.5143404 ,  0.38713795],
       [ 0.9767559 ,  1.31441   ,  0.2761016 ]], dtype=float32)

In [27]:
sess.run(tf.transpose(C))

array([[0.7490754 , 0.81720877, 0.9341235 ],
       [0.36879075, 0.31036377, 0.25892842]], dtype=float32)

In [28]:
sess.run(tf.div(3,5))

0

In [29]:
sess.run(tf.truediv(3,5))

0.6

In [30]:
sess.run(tf.nn.relu([-3., 3., 10.]))

array([ 0.,  3., 10.], dtype=float32)

In [31]:
sess.run(tf.nn.sigmoid([-1., 0, 1.]))

array([0.26894143, 0.5       , 0.7310586 ], dtype=float32)