In [1]:
import numpy as np
import tensorflow as tf

In [2]:
x = tf.range(96)

In [3]:
x = tf.reshape(x, [2,4,4,3])
x

<tf.Tensor: shape=(2, 4, 4, 3), dtype=int32, numpy=
array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]],

        [[24, 25, 26],
         [27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]],

        [[36, 37, 38],
         [39, 40, 41],
         [42, 43, 44],
         [45, 46, 47]]],


       [[[48, 49, 50],
         [51, 52, 53],
         [54, 55, 56],
         [57, 58, 59]],

        [[60, 61, 62],
         [63, 64, 65],
         [66, 67, 68],
         [69, 70, 71]],

        [[72, 73, 74],
         [75, 76, 77],
         [78, 79, 80],
         [81, 82, 83]],

        [[84, 85, 86],
         [87, 88, 89],
         [90, 91, 92],
         [93, 94, 95]]]], dtype=int32)>

In [4]:
x.ndim, x.shape

(4, TensorShape([2, 4, 4, 3]))

In [5]:
y = tf.reshape(x, [2, -1])
y

<tf.Tensor: shape=(2, 48), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
        80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]],
      dtype=int32)>

In [8]:
y = tf.reshape(x, [2, 4, -1])
y

<tf.Tensor: shape=(2, 4, 12), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47]],

       [[48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71],
        [72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
        [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]]], dtype=int32)>

In [17]:
x = tf.random.uniform([28, 28], maxval=10, dtype=tf.int32)
x

<tf.Tensor: shape=(28, 28), dtype=int32, numpy=
array([[9, 6, 1, 1, 6, 8, 9, 0, 0, 5, 8, 3, 1, 9, 0, 8, 4, 8, 1, 0, 9, 3,
        2, 3, 4, 7, 6, 8],
       [1, 7, 8, 1, 0, 1, 0, 3, 1, 3, 0, 0, 8, 9, 1, 6, 5, 9, 9, 4, 0, 8,
        0, 7, 2, 3, 4, 1],
       [3, 0, 6, 1, 5, 1, 4, 1, 3, 2, 4, 2, 0, 9, 8, 9, 2, 3, 7, 6, 3, 1,
        3, 8, 1, 3, 5, 6],
       [4, 0, 7, 5, 6, 5, 3, 4, 9, 2, 4, 0, 5, 0, 6, 5, 4, 8, 9, 4, 5, 8,
        6, 3, 0, 0, 9, 0],
       [6, 9, 7, 7, 1, 6, 2, 9, 9, 5, 6, 7, 2, 8, 0, 5, 6, 0, 1, 1, 9, 0,
        6, 0, 6, 5, 8, 6],
       [7, 7, 2, 2, 3, 7, 9, 6, 9, 2, 6, 5, 3, 4, 3, 5, 2, 1, 2, 4, 7, 4,
        4, 6, 4, 8, 0, 8],
       [7, 2, 1, 5, 5, 1, 2, 9, 9, 1, 9, 9, 2, 5, 9, 5, 6, 9, 3, 6, 0, 4,
        0, 3, 9, 4, 8, 3],
       [0, 7, 7, 4, 2, 0, 9, 0, 7, 4, 0, 9, 4, 6, 3, 7, 7, 7, 2, 1, 8, 7,
        3, 4, 0, 4, 5, 5],
       [2, 1, 8, 7, 8, 1, 0, 1, 4, 5, 9, 5, 5, 9, 0, 3, 6, 3, 5, 7, 2, 7,
        6, 0, 5, 1, 9, 0],
       [0, 1, 5, 8, 4, 7, 2, 4, 2, 5, 2, 4,

In [21]:
y = tf.expand_dims(x, axis=2)
y

<tf.Tensor: shape=(28, 28, 1), dtype=int32, numpy=
array([[[9],
        [6],
        [1],
        [1],
        [6],
        [8],
        [9],
        [0],
        [0],
        [5],
        [8],
        [3],
        [1],
        [9],
        [0],
        [8],
        [4],
        [8],
        [1],
        [0],
        [9],
        [3],
        [2],
        [3],
        [4],
        [7],
        [6],
        [8]],

       [[1],
        [7],
        [8],
        [1],
        [0],
        [1],
        [0],
        [3],
        [1],
        [3],
        [0],
        [0],
        [8],
        [9],
        [1],
        [6],
        [5],
        [9],
        [9],
        [4],
        [0],
        [8],
        [0],
        [7],
        [2],
        [3],
        [4],
        [1]],

       [[3],
        [0],
        [6],
        [1],
        [5],
        [1],
        [4],
        [1],
        [3],
        [2],
        [4],
        [2],
        [0],
        [9],
        [8],
        [9],
        [

In [22]:
z = tf.squeeze(y, axis=2)
z

<tf.Tensor: shape=(28, 28), dtype=int32, numpy=
array([[9, 6, 1, 1, 6, 8, 9, 0, 0, 5, 8, 3, 1, 9, 0, 8, 4, 8, 1, 0, 9, 3,
        2, 3, 4, 7, 6, 8],
       [1, 7, 8, 1, 0, 1, 0, 3, 1, 3, 0, 0, 8, 9, 1, 6, 5, 9, 9, 4, 0, 8,
        0, 7, 2, 3, 4, 1],
       [3, 0, 6, 1, 5, 1, 4, 1, 3, 2, 4, 2, 0, 9, 8, 9, 2, 3, 7, 6, 3, 1,
        3, 8, 1, 3, 5, 6],
       [4, 0, 7, 5, 6, 5, 3, 4, 9, 2, 4, 0, 5, 0, 6, 5, 4, 8, 9, 4, 5, 8,
        6, 3, 0, 0, 9, 0],
       [6, 9, 7, 7, 1, 6, 2, 9, 9, 5, 6, 7, 2, 8, 0, 5, 6, 0, 1, 1, 9, 0,
        6, 0, 6, 5, 8, 6],
       [7, 7, 2, 2, 3, 7, 9, 6, 9, 2, 6, 5, 3, 4, 3, 5, 2, 1, 2, 4, 7, 4,
        4, 6, 4, 8, 0, 8],
       [7, 2, 1, 5, 5, 1, 2, 9, 9, 1, 9, 9, 2, 5, 9, 5, 6, 9, 3, 6, 0, 4,
        0, 3, 9, 4, 8, 3],
       [0, 7, 7, 4, 2, 0, 9, 0, 7, 4, 0, 9, 4, 6, 3, 7, 7, 7, 2, 1, 8, 7,
        3, 4, 0, 4, 5, 5],
       [2, 1, 8, 7, 8, 1, 0, 1, 4, 5, 9, 5, 5, 9, 0, 3, 6, 3, 5, 7, 2, 7,
        6, 0, 5, 1, 9, 0],
       [0, 1, 5, 8, 4, 7, 2, 4, 2, 5, 2, 4,

In [24]:
x = tf.random.normal([2, 32, 32, 2])
tf.transpose(x, perm=[0, 3, 1, 2])

<tf.Tensor: shape=(2, 2, 32, 32), dtype=float32, numpy=
array([[[[-0.66350263,  1.4825099 , -3.3424115 , ..., -0.24520518,
          -1.0310762 ,  0.8222364 ],
         [-0.05601874,  0.8525662 ,  0.38450593, ...,  0.48276207,
           0.257837  ,  1.0978953 ],
         [ 1.8190489 , -1.6396152 ,  0.9056556 , ..., -0.62402505,
           0.33407825,  0.44773367],
         ...,
         [ 0.29311714,  1.2407942 , -2.2430816 , ...,  0.52639174,
          -0.20691945,  0.02994446],
         [-0.19650418,  0.21005988, -0.02333228, ...,  0.2129917 ,
           0.6316905 ,  1.1407052 ],
         [-0.9790801 , -1.0254691 , -1.9907676 , ..., -0.4175731 ,
          -0.31913584,  0.7227937 ]],

        [[ 1.1525108 ,  0.45312172, -0.40809703, ..., -2.3171291 ,
           0.37218374, -2.307642  ],
         [ 0.04291277, -0.49202532, -0.1553829 , ..., -1.5896655 ,
          -0.6203606 , -0.7338104 ],
         [ 2.5886002 , -0.07919356, -0.01323276, ..., -0.8683753 ,
          -0.44837847,  1.045