In [2]:
import numpy as np
import tensorflow as tf

In [3]:
out = tf.random.normal([10,5])
out = tf.nn.softmax(out, axis=1)
print(out)

tf.Tensor(
[[0.32515943 0.03242435 0.12755568 0.36408886 0.15077166]
 [0.21067387 0.05999207 0.14600773 0.36729982 0.21602657]
 [0.10985434 0.7083857  0.0252272  0.12280616 0.03372658]
 [0.20551592 0.46879524 0.07401212 0.20055364 0.05112298]
 [0.26799342 0.04875605 0.26800814 0.18662338 0.22861893]
 [0.08603292 0.3391343  0.12055331 0.25047606 0.2038033 ]
 [0.36165679 0.09165016 0.36943668 0.04327237 0.1339839 ]
 [0.5180245  0.04494635 0.34468785 0.02710288 0.06523838]
 [0.07142196 0.5174532  0.043565   0.23061237 0.1369475 ]
 [0.33894828 0.02947538 0.09869327 0.42488375 0.1079994 ]], shape=(10, 5), dtype=float32)


In [4]:
pred = tf.argmax(out, axis=1)
pred

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([3, 3, 1, 1, 2, 1, 2, 0, 1, 3])>

In [5]:
y = tf.random.uniform([10], dtype=tf.int64, maxval=5)
y

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([1, 0, 2, 0, 2, 2, 2, 2, 0, 2])>

In [6]:
out = tf.equal(pred, y)
out

<tf.Tensor: shape=(10,), dtype=bool, numpy=
array([False, False, False, False,  True, False,  True, False, False,
       False])>

In [7]:
out = tf.cast(out, dtype=tf.float32)
out

<tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 0., 0., 1., 0., 1., 0., 0., 0.], dtype=float32)>

In [8]:
correct = tf.reduce_sum(out)
correct

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [9]:
out = tf.random.normal([4,10])
out

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[-4.7224915e-01,  8.6405092e-01, -2.9416904e-01, -6.4298794e-02,
         7.4310988e-01,  3.4398735e-01,  8.8617903e-01, -1.3819391e+00,
         4.6587907e-04, -9.3558200e-02],
       [-4.1734007e-01, -2.5347400e+00, -2.6854119e-01, -5.2977037e-01,
         1.8924528e-01,  8.7501675e-01,  9.6825039e-01, -1.4290040e+00,
        -1.0428611e+00,  5.4081362e-01],
       [-1.1008236e+00, -1.5160701e+00,  2.9429331e-01,  7.4860686e-01,
         1.0374231e+00,  1.1904374e+00,  1.1957107e+00,  1.2612055e-01,
         1.3987004e+00, -1.7314813e+00],
       [-8.7053955e-01,  1.5185314e+00,  3.2820612e-01,  2.2828650e-01,
        -5.9221089e-01,  4.1097406e-01,  3.4728488e-01, -8.0746210e-01,
         7.3506936e-02, -1.0562756e+00]], dtype=float32)>

In [10]:
y = tf.constant([1,2,2,0])
print(y)
y = tf.one_hot(y, depth=10)
print(y)

tf.Tensor([1 2 2 0], shape=(4,), dtype=int32)
tf.Tensor(
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(4, 10), dtype=float32)


In [12]:
import tensorflow.keras as keras
loss = keras.losses.mse(y, out)
loss

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.37065327, 1.365     , 1.3462125 , 0.8378027 ], dtype=float32)>

In [13]:
loss = tf.reduce_mean(loss)
loss

<tf.Tensor: shape=(), dtype=float32, numpy=0.9799171>

In [15]:
out = tf.random.normal([4, 10])
out = tf.reduce_sum(out, axis=-1)
out

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2.8872852, 1.5895982, 0.8018211, 4.117525 ], dtype=float32)>