In [1]:
import numpy as np
import tensorflow as tf

In [4]:
a = 1.2
aa = tf.constant(1.2)
print(aa)
type(a), type(aa), tf.is_tensor(aa)

tf.Tensor(1.2, shape=(), dtype=float32)


(float, tensorflow.python.framework.ops.EagerTensor, True)

In [6]:
x = tf.constant([1,2.,3.3])
print(x)
x

tf.Tensor([1.  2.  3.3], shape=(3,), dtype=float32)


<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1. , 2. , 3.3], dtype=float32)>

In [7]:
x.numpy()

array([1. , 2. , 3.3], dtype=float32)

In [8]:
x.shape

TensorShape([3])

In [9]:
x.numpy().shape

(3,)

In [13]:
a = tf.constant('Hello 中文')
a

<tf.Tensor: shape=(), dtype=string, numpy=b'Hello \xe4\xb8\xad\xe6\x96\x87'>

In [14]:
tf.strings.lower(a)

<tf.Tensor: shape=(), dtype=string, numpy=b'hello \xe4\xb8\xad\xe6\x96\x87'>

In [16]:
a = tf.constant(True)
print(a)
a is True

tf.Tensor(True, shape=(), dtype=bool)


False

In [17]:
a == True

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [20]:
a.dtype, type(a)

(tf.bool, tensorflow.python.framework.ops.EagerTensor)

In [21]:
tf.cast(a, tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [22]:
a = tf.Variable([1,2])
a

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>