In [1]:
import numpy as np
import tensorflow as tf


In [2]:
a = np.array([[1, 0, 2], [-1, 3, 1]])
a

array([[ 1,  0,  2],
       [-1,  3,  1]])

In [3]:
b = np.array([[3, 1], [2, 1], [1, 0]])
b              

array([[3, 1],
       [2, 1],
       [1, 0]])

In [5]:
c = a + 1
c

array([[2, 1, 3],
       [0, 4, 2]])

$ y = w0 + \sum_{i=0}^{i}x $

In [12]:
# Fully-connected-layer
x = tf.random.normal([2, 784])
w1 = tf.Variable(tf.random.truncated_normal([784, 256], stddev=0.1))
b1 = tf.Variable(tf.zeros([256]))
o1 = tf.matmul(x, w1) + b1
o1[0]

<tf.Tensor: shape=(256,), dtype=float32, numpy=
array([-3.6442037 ,  1.9999719 , -2.9544458 ,  0.07325792,  1.9202785 ,
       -0.9214637 ,  0.26776302, -1.9371636 , -1.9618112 , -2.6975384 ,
        1.8155851 , -3.0879693 ,  4.669779  ,  1.1593285 , -2.0644526 ,
        3.3536599 ,  0.6557804 , -0.8630045 , -0.08942321,  2.9687495 ,
       -4.101213  , -3.606205  , -1.0345474 , -2.50986   , -1.6126463 ,
        2.5153093 , -4.6400847 ,  3.2010455 , -1.0732474 ,  3.685944  ,
       -0.5540576 ,  0.9417107 , -2.1858604 ,  0.15520352,  1.1129565 ,
       -3.8957882 ,  7.304515  ,  3.397481  , -3.1501498 ,  3.2898276 ,
        1.5850515 , -1.6180658 ,  0.43535048, -0.5850909 , -1.228895  ,
        0.25199604, -1.8905172 , -4.408404  , -4.5951033 ,  1.1718409 ,
       -4.286189  , -0.22711796, -5.1445036 ,  1.8409106 ,  1.5368483 ,
       -0.5955237 ,  1.383088  , -0.51921713, -4.415002  , -0.9569485 ,
       -5.032216  , -5.207005  ,  0.59984595, -0.39751858,  2.3840423 ,
       -0.810196

In [16]:
o2 = tf.nn.relu(o1)
o2[0]

<tf.Tensor: shape=(256,), dtype=float32, numpy=
array([0.        , 1.9999719 , 0.        , 0.07325792, 1.9202785 ,
       0.        , 0.26776302, 0.        , 0.        , 0.        ,
       1.8155851 , 0.        , 4.669779  , 1.1593285 , 0.        ,
       3.3536599 , 0.6557804 , 0.        , 0.        , 2.9687495 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       2.5153093 , 0.        , 3.2010455 , 0.        , 3.685944  ,
       0.        , 0.9417107 , 0.        , 0.15520352, 1.1129565 ,
       0.        , 7.304515  , 3.397481  , 0.        , 3.2898276 ,
       1.5850515 , 0.        , 0.43535048, 0.        , 0.        ,
       0.25199604, 0.        , 0.        , 0.        , 1.1718409 ,
       0.        , 0.        , 0.        , 1.8409106 , 1.5368483 ,
       0.        , 1.383088  , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.59984595, 0.        , 2.3840423 ,
       0.        , 4.6660714 , 0.        , 0.        , 1.535254  ,
       1.09431

In [17]:
from tensorflow.keras import layers

fc = layers.Dense(256, activation=tf.nn.relu)
d1 = fc(o1)
d1[0]

<tf.Tensor: shape=(256,), dtype=float32, numpy=
array([0.0000000e+00, 4.0288031e-01, 2.5918548e+00, 0.0000000e+00,
       2.2733090e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 7.6226217e-01,
       7.3005176e-01, 1.7762320e+00, 0.0000000e+00, 1.6574658e+00,
       1.8249588e+00, 0.0000000e+00, 4.4374073e-01, 0.0000000e+00,
       2.6212149e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       5.8169615e-01, 1.2160684e+00, 3.0685229e+00, 2.0812969e-01,
       1.9206938e+00, 8.2649374e-01, 0.0000000e+00, 1.6210135e+00,
       2.3471885e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       3.4371302e+00, 0.0000000e+00, 5.9038645e-01, 0.0000000e+00,
       1.6478995e+00, 1.9375727e+00, 2.7458501e+00, 1.3542519e+00,
       0.0000000e+00, 2.9865537e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 3.4649882e+00, 0.0000000e+00, 3.9630508e+00,
       1.2101653e+00, 0.0000000e+00, 6.4818436e-01, 0.0000000e+00,
       0.00000

In [18]:
fc.kernel

<tf.Variable 'dense_2/kernel:0' shape=(256, 256) dtype=float32, numpy=
array([[ 0.00850622,  0.05124038, -0.10819115, ...,  0.04305591,
        -0.0498781 , -0.01990114],
       [-0.05079612, -0.0760792 ,  0.09573301, ..., -0.06691904,
         0.08058713,  0.00490332],
       [ 0.02806615, -0.00449357,  0.08779977, ..., -0.03465603,
        -0.02754501,  0.06041927],
       ...,
       [ 0.10209715, -0.03597322, -0.01595589, ...,  0.08614429,
         0.09276139, -0.05029977],
       [ 0.03520831,  0.01696419,  0.04672208, ..., -0.09225924,
        -0.09426596, -0.0875724 ],
       [-0.06171762, -0.0536662 ,  0.09108769, ...,  0.04180714,
        -0.04052851,  0.00120391]], dtype=float32)>

In [22]:
x = tf.random.normal([4, 28, 28])
w1 = tf.Variable(tf.random.truncated_normal([784, 4], stddev=0.1))
# h1 = x@w1

In [23]:
x = tf.linspace(-6., 6., 10)
x

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-6.       , -4.6666665, -3.3333333, -2.       , -0.6666665,
        0.666667 ,  2.       ,  3.333334 ,  4.666667 ,  6.       ],
      dtype=float32)>

In [24]:
tf.nn.sigmoid(x)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.00247262, 0.00931596, 0.0344452 , 0.11920292, 0.33924365,
       0.6607564 , 0.880797  , 0.96555483, 0.99068403, 0.9975274 ],
      dtype=float32)>

In [25]:
tf.nn.relu(x)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.      , 0.      , 0.      , 0.      , 0.      , 0.666667,
       2.      , 3.333334, 4.666667, 6.      ], dtype=float32)>

In [30]:
from itertools import count
d = count(0)
print(next(d))
print(next(d))

from collections import defaultdict
label2index = defaultdict(lambda: next(d))
label2index

0
1


defaultdict(<function __main__.<lambda>()>, {})

In [32]:
from scipy.sparse import csr_matrix
import numpy as np

indptr = np.array([0,2,3,6])
indices = np.array([0,2,2,0,1,2])
data = np.array([1,2,3,4,5,6])
csr_matrix_0 = csr_matrix((data,indices,indptr),shape=(3,3))
print(csr_matrix_0.toarray())
print(csr_matrix_0.todense())

[[1 0 2]
 [0 0 3]
 [4 5 6]]
[[1 0 2]
 [0 0 3]
 [4 5 6]]


In [44]:
from scipy import sparse
import numpy as np

row = np.array([0, 3, 1, 0])
col = np.array([0, 3, 1, 2])
data = np.array([6, 5, 7, 8])

# Coordinate (COO)
# 生成矩阵
# data[i] = X[row][col]
# data[0] = 6，生成的矩阵 X[0][0] = 6
sparse.coo_matrix((data, (row, col)), shape=(4,4)).toarray()

array([[6, 0, 8, 0],
       [0, 7, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 5]])

In [40]:
from scipy import sparse
import numpy as np

indptr = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])

# Compressed Sparse Column (CSC)
# 生成矩阵
# indptr:  代表矩阵中每一列所存的数在data中的开始和结束索引（左闭右开）
#          上例indptr有3列：[0,2) [2,3) [3,6)
#          表示data[0,2)即 1,2 放在第 1 列，data[2,3)即 3 放在第 2 列           
# indices: 代表data[i]中的数据位于矩阵的行数
#          上例indices[0]表示data[0]即 1 放在第 0 行
#          上例indices[1]表示data[1]即 2 放在第 2 行 
sparse.csc_matrix((data, indices, indptr), shape=(3, 3)).todense()

matrix([[1, 0, 4],
        [0, 0, 5],
        [2, 3, 6]])

In [41]:
from scipy import sparse
import numpy as np

indptr = np.array([0, 2, 3, 6])
indices = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])

# Compressed Sparse Row (CSR)
# 生成矩阵
# indptr:  代表矩阵中每一行所存的数在data中的开始和结束索引（左闭右开）
#          上例indptr有3行：[0,2) [2,3) [3,6)
#          表示data[0,2)即 1,2 放在第 1 行，data[2,3)即 3 放在第 2 行
# indices: 代表data[i]中的数据放在矩阵的列数
#          上例indices[0]表示data[0]即 1 放在第 0 列
#          上例indices[1]表示data[1]即 2 放在第 2 列 
sparse.csr_matrix((data, indices, indptr), shape=(3, 3)).todense()

matrix([[1, 0, 2],
        [0, 0, 3],
        [4, 5, 6]])

In [46]:
from scipy import sparse
import numpy as np

row = np.array([0, 3, 1, 0])
col = np.array([0, 3, 1, 2])
data = np.array([6, 5, 7, 8])
sparse.csr_matrix((data, (row, col)), shape=(4, 4)).todense()

matrix([[6, 0, 8, 0],
        [0, 7, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 5]], dtype=int64)

In [64]:
from scipy import sparse
import numpy as np

row = np.repeat(np.arange(10), 2)
print(row)
col = np.array([0,1,0,2,0,3,0,4,0,5,0,6,0,7,0,8,0,9,0,10])
print(col)
data = np.ones(20)
print(data)
m1 = sparse.csr_matrix((data, (row, col)), shape=(10, 11)).todense()

[0 0 1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9]
[ 0  1  0  2  0  3  0  4  0  5  0  6  0  7  0  8  0  9  0 10]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [65]:
from scipy import sparse
import numpy as np

row = np.repeat(np.arange(10), 2)
print(row)
col = np.array([0,11,1,12,1,13,1,14,2,15,2,16,3,17,4,18,5,19,1,20])
print(col)
data = np.ones(20)
print(data)
m2 = sparse.csr_matrix((data, (row, col)), shape=(20, 21)).toarray()

[0 0 1 1 2 2 3 3 4 4 5 5 6 6 7 7 8 8 9 9]
[ 0 11  1 12  1 13  1 14  2 15  2 16  3 17  4 18  5 19  1 20]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [67]:
from sklearn.feature_extraction import DictVectorizer
a = [{'user': 'u_1', 'item': 'i_1'},
 {'user': 'u_1', 'item': 'i_2'},
 {'user': 'u_2', 'item': 'i_3'},
 {'user': 'u_1', 'item': 'i_4'},
 {'user': 'u_1', 'item': 'i_5'},
 {'user': 'u_2', 'item': 'i_6'},
 {'user': 'u_3', 'item': 'i_7'},
 {'user': 'u_3', 'item': 'i_8'},
 {'user': 'u_1', 'item': 'i_9'},
 {'user': 'u_1', 'item': 'i_10'}]

vec = DictVectorizer()
vec.fit_transform(a)

<10x13 sparse matrix of type '<class 'numpy.float64'>'
	with 20 stored elements in Compressed Sparse Row format>

In [68]:
b = [{'user': 'u_1', 'item': 'i_2'},
 {'user': 'u_2', 'item': 'i_2'},
 {'user': 'u_3', 'item': 'i_3'}]
x_train = vec.transform(b).toarray()
x_train

array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])