In [1]:
import numpy as np
import tensorflow as tf

In [3]:
z = tf.random.normal([2, 10])
print(z)
y = tf.constant([1, 3])
print(y)
y_onehot = tf.one_hot(y, depth=10)
print(y_onehot)

tf.Tensor(
[[-1.8308574  -0.3758942  -0.53717446  0.04598429 -0.04517663  0.73741436
  -0.54107165 -0.69083977  0.8131743   0.49534595]
 [ 0.688431    0.53288376  0.4322467  -0.32048616  0.903399   -1.5060809
  -0.17908491  1.1635654  -2.0824494  -1.2499871 ]], shape=(2, 10), dtype=float32)
tf.Tensor([1 3], shape=(2,), dtype=int32)
tf.Tensor(
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]], shape=(2, 10), dtype=float32)


In [7]:
loss = tf.keras.losses.categorical_crossentropy(y_onehot, z, from_logits=True)
loss = tf.reduce_mean(loss)
loss

<tf.Tensor: shape=(), dtype=float32, numpy=2.810351>