In [1]:
import numpy as np
import tensorflow as tf

In [5]:
# 生成一个矩阵
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
x.shape

(5, 2)

In [12]:
# 生成标签列
y = np.arange(5)
y = np.reshape(y, (-1, 1))
y

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [14]:
feats = tf.convert_to_tensor(x)
feats

<tf.Tensor: shape=(5, 2), dtype=int64, numpy=
array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])>

In [26]:
train_db = tf.data.Dataset.from_tensor_slices((x, y))
train_db = train_db.shuffle(100).batch(2)
list(train_db.as_numpy_iterator())

[(array([[3, 4],
         [1, 2]]),
  array([[1],
         [0]])),
 (array([[ 9, 10],
         [ 5,  6]]),
  array([[4],
         [2]])),
 (array([[7, 8]]), array([[3]]))]

In [21]:
for step, (x_train, y_train) in enumerate(train_db):
    print('step=', step, x_train, y_train)

step= 0 tf.Tensor(
[[1 2]
 [5 6]], shape=(2, 2), dtype=int64) tf.Tensor(
[[0]
 [2]], shape=(2, 1), dtype=int64)
step= 1 tf.Tensor(
[[3 4]
 [7 8]], shape=(2, 2), dtype=int64) tf.Tensor(
[[1]
 [3]], shape=(2, 1), dtype=int64)
step= 2 tf.Tensor([[ 9 10]], shape=(1, 2), dtype=int64) tf.Tensor([[4]], shape=(1, 1), dtype=int64)


In [27]:
# 测试train_db的iterator
for i in range(10):
    for step, (x_train, y_train) in enumerate(train_db):
        print('>>> i =', i, 'step =', step, x_train.numpy(), y_train.numpy())


>>> i = 0 step = 0 [[7 8]
 [1 2]] [[3]
 [0]]
>>> i = 0 step = 1 [[ 9 10]
 [ 5  6]] [[4]
 [2]]
>>> i = 0 step = 2 [[3 4]] [[1]]
>>> i = 0 step = 0 [[1 2]
 [5 6]] [[0]
 [2]]
>>> i = 0 step = 1 [[ 3  4]
 [ 9 10]] [[1]
 [4]]
>>> i = 0 step = 2 [[7 8]] [[3]]
>>> i = 1 step = 0 [[ 9 10]
 [ 3  4]] [[4]
 [1]]
>>> i = 1 step = 1 [[5 6]
 [1 2]] [[2]
 [0]]
>>> i = 1 step = 2 [[7 8]] [[3]]
>>> i = 1 step = 0 [[3 4]
 [5 6]] [[1]
 [2]]
>>> i = 1 step = 1 [[ 7  8]
 [ 9 10]] [[3]
 [4]]
>>> i = 1 step = 2 [[1 2]] [[0]]
>>> i = 2 step = 0 [[5 6]
 [3 4]] [[2]
 [1]]
>>> i = 2 step = 1 [[ 9 10]
 [ 7  8]] [[4]
 [3]]
>>> i = 2 step = 2 [[1 2]] [[0]]
>>> i = 2 step = 0 [[3 4]
 [1 2]] [[1]
 [0]]
>>> i = 2 step = 1 [[ 9 10]
 [ 5  6]] [[4]
 [2]]
>>> i = 2 step = 2 [[7 8]] [[3]]
>>> i = 3 step = 0 [[ 3  4]
 [ 9 10]] [[1]
 [4]]
>>> i = 3 step = 1 [[5 6]
 [1 2]] [[2]
 [0]]
>>> i = 3 step = 2 [[7 8]] [[3]]
>>> i = 3 step = 0 [[3 4]
 [1 2]] [[1]
 [0]]
>>> i = 3 step = 1 [[7 8]
 [5 6]] [[3]
 [2]]
>>> i = 3 step = 2 [[