In [1]:
import numpy as np
import tensorflow as tf

In [2]:
tf.zeros([])

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [3]:
tf.random.normal([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.58964705, -0.77998286],
       [ 1.1123979 ,  0.3973646 ]], dtype=float32)>

In [4]:
tf.random.uniform([2,2])

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.24602425, 0.42403388],
       [0.52626646, 0.00264955]], dtype=float32)>

In [6]:
out = tf.random.uniform([4,10])
print(out)
y = tf.constant([2,3,2,0])
print(y)
y = tf.one_hot(y, depth=10)
print(y)
loss = tf.keras.losses.mse(y, out)
print(loss)
loss = tf.reduce_mean(loss)
print(loss)

tf.Tensor(
[[0.8466885  0.5517901  0.5153737  0.8980526  0.6672832  0.8628347
  0.4610952  0.30387795 0.26763284 0.6299341 ]
 [0.1865766  0.95328534 0.02492011 0.42514205 0.35795343 0.895267
  0.6278577  0.12264204 0.5296699  0.37083805]
 [0.16201186 0.84440637 0.24263144 0.08350801 0.9386245  0.27933967
  0.74174666 0.44460034 0.29703867 0.680681  ]
 [0.95341086 0.2125107  0.5915729  0.13903153 0.07715642 0.6889435
  0.56989956 0.6233692  0.03786147 0.8945997 ]], shape=(4, 10), dtype=float32)
tf.Tensor([2 3 2 0], shape=(4,), dtype=int32)
tf.Tensor(
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(4, 10), dtype=float32)
tf.Tensor([0.40258604 0.30315974 0.35783133 0.24123326], shape=(4,), dtype=float32)
tf.Tensor(0.3262026, shape=(), dtype=float32)


In [8]:
a = tf.random.normal([4,2])
b = tf.zeros([2])
z = a + b
z

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[-0.87612295, -0.51981354],
       [-0.909684  ,  0.1952527 ],
       [-0.65551054,  1.4818776 ],
       [ 1.3520427 , -0.7577985 ]], dtype=float32)>

In [9]:
fc = tf.keras.layers.Dense(3)
print(fc)

In [10]:
fc.build(input_shape=(2,4))
print(fc)

In [11]:
fc.bias

<tf.Variable 'bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [13]:
(x_train, y_train),(x_test, y_test) = tf.keras.datasets.imdb.load_data(num_words=10000)
x_train = tf.keras.preprocessing.sequence.pad_sequences(x_train, maxlen=80)
x_train.shape

(25000, 80)

In [14]:
embedding = tf.keras.layers.Embedding(10000, 100)
out = embedding(x_train)
out.shape

TensorShape([25000, 80, 100])