In [1]:
import numpy as np
import tensorflow as tf

In [2]:
a = tf.range(5)
b = tf.constant(2)
a, b

(<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 1, 2, 3, 4], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [3]:
a // b

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 1, 1, 2], dtype=int32)>

In [4]:
x = tf.range(4)
tf.pow(x, 3)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 0,  1,  8, 27], dtype=int32)>

In [6]:
x = tf.constant([1., 4., 9.])
x ** 0.5

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [8]:
x = tf.range(5)
x = tf.cast(x, dtype=tf.float32)
x = tf.square(x)
x

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 0.,  1.,  4.,  9., 16.], dtype=float32)>

In [9]:
tf.sqrt(x)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 1., 2., 3., 4.], dtype=float32)>

In [11]:
tf.exp(1.)

<tf.Tensor: shape=(), dtype=float32, numpy=2.7182817>

In [12]:
x = tf.constant([1., 2.])
x = 10 ** x
x

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 10., 100.], dtype=float32)>

In [13]:
tf.math.log(x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.3025851, 4.6051702], dtype=float32)>

In [14]:
tf.math.log(x) / tf.math.log(10.)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [16]:
a = tf.random.normal([3, 2, 28, 32])
b = tf.random.normal([3, 2, 32, 4])
c = a @ b
c.shape

TensorShape([3, 2, 28, 4])

In [18]:
c = tf.matmul(a, b)
c.shape

TensorShape([3, 2, 28, 4])

In [23]:
a = tf.random.normal([2, 3])
b = tf.random.normal([3])
c = tf.multiply(a, b)
c.shape

TensorShape([2, 3])