In [1]:
import numpy as np
import tensorflow as tf

In [2]:
a = tf.random.normal([3,5,3])
a

<tf.Tensor: shape=(3, 5, 3), dtype=float32, numpy=
array([[[ 1.3821359 , -1.6439056 ,  0.6655175 ],
        [ 0.4448533 ,  0.23952235, -1.3671277 ],
        [-0.86957103, -0.38396072, -1.1867595 ],
        [ 0.44460648, -0.35059476, -0.28964812],
        [-0.36335507, -0.59924877,  1.1892275 ]],

       [[-0.36804935, -0.8937473 ,  0.64367265],
        [ 0.4536819 , -0.09652387,  1.5960388 ],
        [ 0.6771526 ,  0.5496152 , -1.8920588 ],
        [ 1.1047348 , -0.14855884,  1.0256959 ],
        [ 0.11284781, -0.78653723, -2.74951   ]],

       [[ 2.3341322 ,  0.07718401,  1.0118115 ],
        [ 0.56736916, -1.8911982 ,  0.94348705],
        [-0.79237145,  1.3536762 ,  1.2823409 ],
        [ 0.47058952,  0.5876878 ,  0.02963732],
        [-2.9690912 ,  1.2093885 , -0.22212134]]], dtype=float32)>

In [3]:
b = tf.random.normal([2,5,3])
b

<tf.Tensor: shape=(2, 5, 3), dtype=float32, numpy=
array([[[-1.2022417 , -0.13763706,  0.31774998],
        [ 2.3945696 ,  2.52795   ,  0.28484592],
        [-2.4245741 , -0.02016445, -1.6517588 ],
        [-0.47223037, -0.9146342 ,  1.42801   ],
        [-0.7643605 , -0.3698931 ,  0.3075182 ]],

       [[ 0.7545591 , -1.5402629 ,  0.39431953],
        [-0.9182761 , -1.1272552 , -1.0664238 ],
        [-0.9225227 ,  0.57233506, -1.7554173 ],
        [-0.56660753, -0.33441806,  0.21268603],
        [ 0.6358022 , -0.7437283 ,  0.30678728]]], dtype=float32)>

In [4]:
c = tf.concat([a, b], axis=0)
c

<tf.Tensor: shape=(5, 5, 3), dtype=float32, numpy=
array([[[ 1.3821359 , -1.6439056 ,  0.6655175 ],
        [ 0.4448533 ,  0.23952235, -1.3671277 ],
        [-0.86957103, -0.38396072, -1.1867595 ],
        [ 0.44460648, -0.35059476, -0.28964812],
        [-0.36335507, -0.59924877,  1.1892275 ]],

       [[-0.36804935, -0.8937473 ,  0.64367265],
        [ 0.4536819 , -0.09652387,  1.5960388 ],
        [ 0.6771526 ,  0.5496152 , -1.8920588 ],
        [ 1.1047348 , -0.14855884,  1.0256959 ],
        [ 0.11284781, -0.78653723, -2.74951   ]],

       [[ 2.3341322 ,  0.07718401,  1.0118115 ],
        [ 0.56736916, -1.8911982 ,  0.94348705],
        [-0.79237145,  1.3536762 ,  1.2823409 ],
        [ 0.47058952,  0.5876878 ,  0.02963732],
        [-2.9690912 ,  1.2093885 , -0.22212134]],

       [[-1.2022417 , -0.13763706,  0.31774998],
        [ 2.3945696 ,  2.52795   ,  0.28484592],
        [-2.4245741 , -0.02016445, -1.6517588 ],
        [-0.47223037, -0.9146342 ,  1.42801   ],
        [-0.

In [5]:
out = tf.random.normal([2, 10])
print(out)
out = tf.nn.softmax(out, axis=1)
print(out)

tf.Tensor(
[[-0.6733704  -0.8894947  -0.08664213  0.717914    0.22397134  0.9927347
   0.26868966  0.39462984 -0.23225164  0.6369063 ]
 [-0.11201511  1.0384492  -1.4605044  -1.9895926  -0.5046352  -0.6709823
   1.0373805   0.6053884   0.46768206 -0.3358627 ]], shape=(2, 10), dtype=float32)
tf.Tensor(
[[0.03830714 0.03086158 0.06887991 0.1539951  0.09397024 0.20270291
  0.0982678  0.11145674 0.05954636 0.14201221]
 [0.07347721 0.23216297 0.01907705 0.01123909 0.04961808 0.04201422
  0.231915   0.15056257 0.13119338 0.0587404 ]], shape=(2, 10), dtype=float32)


In [6]:
pred = tf.argmax(out, axis=1)
pred

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([5, 1])>

In [7]:
pred = tf.argmin(out, axis=1)
pred

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 3])>