In [1]:
import mxnet as mx

from mxnet import nd
from mxnet import np, npx

In [3]:
# when using tensors, we almost always invoke the set_np()
# this is for compatibility of tensor processing by other components of MXNet
npx.set_np()

In [4]:
# broadcast mechanism
a = np.arange(3).reshape(3, 1)
b = np.arange(2).reshape(1, 2)
a, b

(array([[0.],
        [1.],
        [2.]]),
 array([[0., 1.]]))

In [5]:
a + b

array([[0., 1.],
       [1., 2.],
       [2., 3.]])

In [6]:
a = np.array([3.5])
a, a.item(), float(a), int(a)

(array([3.5]), 3.5, 3.5, 3)

In [9]:
# memory saving
Y = np.array([[1, 2], [3, 4]])
print('id(Y)', id(Y))
print(Y)

Z = np.zeros_like(Y)
print('id(Z)', id(Z))
print(Z)
Z[:] = Y + 1
print('id(Z)', id(Z))
print(Z)

id(Y) 140364917707904
[[1. 2.]
 [3. 4.]]
id(Z) 140364917710208
[[0. 0.]
 [0. 0.]]
id(Z) 140364917710208
[[2. 3.]
 [4. 5.]]
