In [2]:
import mxnet as mx
from mxnet import nd
from mxnet import np, npx

In [3]:
npx.set_np()

In [4]:
x = np.arange(12)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [5]:
x = x.reshape(3, 4)
x

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [6]:
x = np.array([1, 2, 4, 8])
y = np.array([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(array([ 3.,  4.,  6., 10.]),
 array([-1.,  0.,  2.,  6.]),
 array([ 2.,  4.,  8., 16.]),
 array([0.5, 1. , 2. , 4. ]),
 array([ 1.,  4., 16., 64.]))

In [7]:
a = nd.ones([2, 3])
a


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [8]:
nd.zeros((2, 3, 4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

In [9]:
a = np.log(2)
a

0.6931471805599453

In [10]:
b = np.log(3)
b

1.0986122886681098

In [11]:
a + b

1.791759469228055

In [12]:
a = nd.arange(3)
a


[0. 1. 2.]
<NDArray 3 @cpu(0)>

In [16]:
# create a tensor with each of it's elements is
# randomly sampled from a standard gaurassian distribution
# with a mean of 0 and 
# a standard deviation of 1

s = np.random.normal(0, 1, size=(3, 4))
s.shape

(3, 4)