In [1]:
import keras
from keras.layers import Input, Dense
from keras.models import Model


Using TensorFlow backend.


In [2]:
# this returns a tensor
inputs = Input(shape=(784,))

# a layer instance is callable on tensor, and return s a tensor
x = Dense(64, activation='relu')(inputs)
x = Dense(64, activation='relu')(x)
predictions = Dense(10, activation='softmax')(x)

# This is creates a model that includes
# the input layer and three dense layers
model = Model(inputs=inputs, outputs=predictions)
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 784)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_3 (Dense)              (None, 10)                650       
Total params: 55,050
Trainable params: 55,050
Non-trainable params: 0
_________________________________________________________________


In [15]:
# generate dummy data
import numpy as np
data = np.random.random((1000, 784))
labels = np.random.randint(10, size=(1000, 10))

print(data)
print(labels.shape)

model.fit(data, labels, epochs=10, batch_size=32)

[[0.8618657  0.96751355 0.34268598 ... 0.17564383 0.41026474 0.67666894]
 [0.01930313 0.45726195 0.81104451 ... 0.39949187 0.95561441 0.68909081]
 [0.03411247 0.79656284 0.09232703 ... 0.42693263 0.66578953 0.78988888]
 ...
 [0.3191208  0.91566354 0.01272379 ... 0.65785892 0.02566276 0.13494665]
 [0.76459975 0.61994027 0.59666149 ... 0.49578845 0.48464921 0.17918464]
 [0.33860232 0.00806819 0.83960939 ... 0.54289271 0.21237702 0.20826553]]
(1000, 10)
Epoch 1/10
1000/1000 [==============================] - 0s 47us/step - loss: 103.2875 - acc: 0.0970
Epoch 2/10
1000/1000 [==============================] - 0s 47us/step - loss: 103.2156 - acc: 0.0870
Epoch 3/10
1000/1000 [==============================] - 0s 47us/step - loss: 103.2152 - acc: 0.1010
Epoch 4/10
1000/1000 [==============================] - 0s 45us/step - loss: 103.1994 - acc: 0.0930
Epoch 5/10
1000/1000 [==============================] - 0s 47us/step - loss: 103.1914 - acc: 0.0900
Epoch 6/10
1000/1000 [=======================